messageFrench = "Salut {name}, *c'est Gui du Dunamis Greenhouse Europe*  👋🏼, et c'est un plaisir de rencontrer quelqu'un qui veut apporter le Réveil en {country} ! 🔥  \n\n Il y a quelques semaines, tu t'es inscrit(e) au Dunamis Greenhouse, mais je crois que tu n'as pas reçu notre e-mail. Il a été envoyé à {email} et il est probablement tombé dans tes spams. 😭  \n Nous aimerions t'aider à discerner la voix de Dieu dans cette décision. Pouvons-nous planifier un appel de 15 minutes aux dates suivantes ?  \n\n 👉 *Lien pour planifier l'appel* 🔗 [link]  \n\n Au plaisir de t'entendre ! 🤗  \n _L'équipe Dunamis Greenhouse_"

messageEnglish = "Hey {name}, *it’s Gui from Dunamis Greenhouse Europe* 👋🏼 and it's a pleasure meeting someone who wants to bring Revival to {country}! 🔥  \n\n A couple of weeks ago you enrolled for Dunamis Greenhouse but I believe you didn't get our email. It was sent to {email} and probably went to your spam folder. 😭  \n We want to talk to you to help discerning God’s voice in this decision, can we schedule a 15 min call on the following days?  \n\n 👉 *Schedule call link* 🔗 [link]  \n\n Looking forward to speaking with you! 🤗  \n _Dunamis Greenhouse Team_"

messageSpanish = "Hola, {name}, *soy Gui de Dunamis Greenhouse Europe* 👋🏼, y es un placer conocer a alguien que quiere traer Avivamiento a {country}! 🔥  \n\n Hace unas semanas te inscribiste en Dunamis Greenhouse, pero creo que no recibiste nuestro correo electrónico. Fue enviado a {email} y probablemente llegó a tu carpeta de spam. 😭  \n Queremos hablar contigo para ayudarte a discernir la voz de Dios en esta decisión. ¿Podemos programar una llamada de 15 minutos en los siguientes días?  \n\n 👉 *Enlace para programar la llamada* 🔗 [link]  \n\n ¡Esperamos con ansias hablar contigo! 🤗  \n _El equipo de Dunamis Greenhouse_"

messagePortuguese = "Oi, {name}, *aqui é o Gui da Dunamis Greenhouse Europe* 👋🏼, e é um prazer conhecer alguém que quer trazer Avivamento para {country}! 🔥  \n\n Algumas semanas atrás, você se inscreveu no Dunamis Greenhouse, mas acredito que não recebeu nosso e-mail. Ele foi enviado para {email} e provavelmente caiu na sua pasta de spam. 😭  \n Queremos conversar com você para ajudar a discernir a voz de Deus nessa decisão. Podemos agendar uma ligação de 15 minutos nos próximos dias?  \n\n 👉 *Link para agendar a ligação* 🔗 [link]  \n\n Estamos ansiosos para falar com você! 🤗  \n _Equipe Dunamis Greenhouse_"

messageItalian = "Ciao, {name}, *sono Gui di Dunamis Greenhouse Europe* 👋🏼, ed è un piacere conoscere qualcuno che vuole portare il Risveglio in {country}! 🔥  \n\n Qualche settimana fa hai iscritto per Dunamis Greenhouse, ma credo che tu non abbia ricevuto la nostra email. È stata inviata a {email} ed è probabilmente finita nella tua cartella spam. 😭  \n Vogliamo parlarti per aiutarti a discernire la voce di Dio in questa decisione. Possiamo programmare una chiamata di 15 minuti nei prossimi giorni?  \n\n 👉 *Link per programmare la chiamata* 🔗 [link]  \n\n Non vediamo l'ora di parlarti! 🤗  \n _Il team di Dunamis Greenhouse_"

messageGerman = "Hallo, {name}, *hier ist Gui von Dunamis Greenhouse Europe* 👋🏼, und es ist eine Freude, jemanden kennenzulernen, der Erweckung nach {country} bringen möchte! 🔥  \n\n Vor ein paar Wochen hast du dich für Dunamis Greenhouse angemeldet, aber ich glaube, du hast unsere E-Mail nicht erhalten. Sie wurde an {email} gesendet und ist wahrscheinlich in deinem Spam-Ordner gelandet. 😭  \n Wir möchten mit dir sprechen, um dir zu helfen, Gottes Stimme in dieser Entscheidung zu hören. Können wir einen 15-minütigen Anruf in den nächsten Tagen vereinbaren?  \n\n 👉 *Link zur Terminvereinbarung* 🔗 [link]  \n\n Wir freuen uns darauf, mit dir zu sprechen! 🤗  \n _Das Dunamis Greenhouse Team_"